/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StringArray = string[];

export interface OpenLibraryAuthorSchema {
  key: string;
  name: string;
  type: {
    key?: "/type/author";
  };
  alternate_names?: StringArray;
  bio?: TextBlock;
  birth_date?: string;
  death_date?: string;
  location?: string;
  date?: string;
  entity_type?: "person" | "org" | "event";
  fuller_name?: string;
  personal_name?: string;
  title?: string;
  photos?: number[];
  links?: Link[];
  remote_ids?: {
    wikidata?: string;
    viaf?: string;
    [k: string]: unknown;
  };
  /**
   * DEPRECATED: Not many authors have this property. Should be moved to Links and/or remote_ids: wikidata.
   */
  wikipedia?: string;
  revision: number;
  latest_revision?: number;
  created?: InternalDatetime;
  last_modified: InternalDatetime;
}
export interface TextBlock {
  type: "/type/text";
  value: string;
}
export interface Link {
  url: string;
  title: string;
  type?: {
    key: "/type/link";
  };
}
export interface InternalDatetime {
  type: "/type/datetime";
  value: string;
}
