/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * @minItems 1
 * @maxItems 1
 */
export type Works = [
  {
    key: string;
  }
];
export type Isbn_10 = string;
export type Isbn_13 = string;
/**
 * Library of Congress Control Numbers, linkable via https://lccn.loc.gov/<lccn>
 */
export type LibraryOfCongressControlNumbers = string[];
/**
 * Links to the Internet Archive record via https://archive.org/details/<ocaid>
 */
export type InternetArchiveOCAID = string;
export type StringArray = string[];

export interface OpenLibraryEditionSchema {
  key: string;
  title: string;
  subtitle?: string;
  type: {
    key?: "/type/edition";
  };
  authors?: Author[];
  works: Works;
  identifiers?: Identifiers;
  isbn_10?: Isbn_10[];
  isbn_13?: Isbn_13[];
  lccn?: LibraryOfCongressControlNumbers;
  ocaid?: InternetArchiveOCAID;
  /**
   * OCLC Online Computer Library Center / WorldCat id, linkable via https://www.worldcat.org/oclc/<oclc_number>
   */
  oclc_numbers?: string[];
  local_id?: string[];
  covers?: number[];
  links?: Link[];
  languages?: Language[];
  /**
   * Translated from original language(s)
   */
  translated_from?: Language[];
  /**
   * The title of the original language work
   */
  translation_of?: string;
  by_statement?: string;
  weight?: string;
  edition_name?: string;
  number_of_pages?: number;
  pagination?: string;
  physical_dimensions?: string;
  physical_format?: string;
  copyright_date?: string;
  /**
   * The MARC21 country code. See https://www.loc.gov/marc/countries/cou_home.html
   */
  publish_country?: string;
  /**
   * The publication date in Extended Date/Time Format (EDTF) -- https://www.loc.gov/standards/datetime/
   */
  publish_date?: string;
  publish_places?: StringArray;
  publishers?: StringArray;
  contributions?: StringArray;
  dewey_decimal_class?: StringArray;
  genres?: StringArray;
  lc_classifications?: string[];
  other_titles?: StringArray;
  series?: StringArray;
  source_records?: StringArray;
  subjects?: StringArray;
  work_titles?: StringArray;
  table_of_contents?: unknown[];
  description?: TextBlock;
  first_sentence?: TextBlock;
  notes?: TextBlock;
  revision: number;
  latest_revision?: number;
  created?: InternalDatetime;
  last_modified: InternalDatetime;
}
export interface Author {
  key: string;
}
export interface Identifiers {
  [k: string]: unknown;
}
export interface Link {
  url: string;
  title: string;
  type?: {
    key: "/type/link";
  };
}
/**
 * A type based on the list of MARC21 language codes. See https://www.loc.gov/marc/languages/
 */
export interface Language {
  key: string;
}
export interface TextBlock {
  type: "/type/text";
  value: string;
}
export interface InternalDatetime {
  type: "/type/datetime";
  value: string;
}
