/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type StringArray = string[];

export interface OpenLibraryWorkSchema {
  key: string;
  title: string;
  subtitle?: string;
  type: {
    key?: "/type/work";
  };
  authors?: {
    [k: string]: unknown;
  }[];
  covers?: number[];
  links?: Link[];
  /**
   * Unsure what this is for, deprecate?
   */
  id?: number;
  lc_classifications?: StringArray;
  subjects?: StringArray;
  first_publish_date?: string;
  description?: TextBlock;
  notes?: TextBlock;
  revision: number;
  latest_revision?: number;
  created?: InternalDatetime;
  last_modified: InternalDatetime;
  [k: string]: unknown;
}
export interface Link {
  url: string;
  title: string;
  type?: {
    key: "/type/link";
  };
}
export interface TextBlock {
  type: "/type/text";
  value: string;
}
export interface InternalDatetime {
  type: "/type/datetime";
  value: string;
}
