export const TAURI_INTEGRATION_PORT = 3099
export const TAURI_INTEGRATION_BASE_URL = `http://localhost:${TAURI_INTEGRATION_PORT}`
export const TAURI_INTEGRATION_HEALTH_URL = `${TAURI_INTEGRATION_BASE_URL}/up`
